---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-demo
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |-
    route:
        group_by: ["alertname"]
        group_wait: 30s
        group_interval: 1m
        receiver: "send_email"
    receivers:
        - name: "send_email"
          email_configs:
          - to: fayssalelmekkaoui@gmail.com
            from: fayssalelmekkaoui1@gmail.com
            smarthost: smtp.gmail.com:587
            auth_username: fayssalelmekkaoui1@gmail.com
            auth_password: acab1312
            auth_identity: fayssalelmekkaoui1@gmail.com
    inhibit_rules:
    - source_match:
          severity: 'critical'
      target_match:
          severity: 'warning'
      equal: ['alertname', 'dev', 'instance']


