---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: general
  namespace: monitoring
  labels:
    team: devops-by-example
spec:
  groups:
  - name: general
    rules:
    - alert: TargetDown
      annotations:
        message: '{{ $value }}% of the {{ $labels.job }} targets are down.'
      expr: node_memory_Active_bytes > 1000
      for: 1m
      labels:
        severity: warning
