---
- name: Run Prometheus on K8s
  hosts: all

  tasks:

     - name: apply crds
       shell: kubectl apply -f "{{ lookup('env','PWD') }}/crds"
     
     - name: deploy prometheus-operator
       shell: kubectl apply -f "{{ lookup('env','PWD') }}/prometheus-operator/"

     - name: deploy prometheus
       shell: kubectl apply -f "{{ lookup('env','PWD') }}/prometheus/"

     - name: cadvisor
       shell: kubectl apply -f "{{ lookup('env','PWD') }}/cadvisor/"

     - name: deploy alermanager
       shell: kubectl apply -f "{{ lookup('env','PWD') }}/alertmanager/"

     - name: deploy grafana
       shell: kubectl apply -f "{{ lookup('env','PWD') }}/grafana/"

     - name: deploy node-exporter
       shell: kubectl apply -f "{{ lookup('env','PWD') }}/node-exporter/"
     
     - name: deploy kube-state-metrics
       shell: kubectl apply -f "{{ lookup('env','PWD') }}/kube-state-metrics/"

       

 
