---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    team: devops-by-example
spec:
  endpoints:
  - honorLabels: true
    port: http
  selector:
    matchLabels:
       app: cadvisor
