---
kind: Service
apiVersion: v1
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    app: cadvisor
spec:
  selector:
       app: vrops-cadvisor
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080

    
