---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    team: devops-by-example
spec:
  endpoints:
  - honorLabels: true
    port: node-exporter
  selector:
    matchLabels:
      app: node-exporter
